export const legalSlots = [
  {
    id: 1,
    date: "2026-05-07",
    start: "09:00",
    end: "09:30",
    capacity: 3,
    booked: 2,
    status: "متاح",
    note: "جلسة صباحية",
  },
  {
    id: 2,
    date: "2026-05-07",
    start: "10:00",
    end: "10:30",
    capacity: 2,
    booked: 2,
    status: "محجوز",
    note: "مكتمل",
  },
  {
    id: 3,
    date: "2026-05-08",
    start: "12:00",
    end: "12:30",
    capacity: 4,
    booked: 1,
    status: "متاح",
    note: "وقت مناسب للاستقبال",
  },
  {
    id: 4,
    date: "2026-05-08",
    start: "15:00",
    end: "15:30",
    capacity: 2,
    booked: 0,
    status: "مغلق",
    note: "إغلاق مؤقت",
  },
];

export const legalEngineers = [
  {
    id: 1,
    name: "أحمد صالح",
    phone: "+963 988 123 456",
    email: "ahmad@example.com",
    specialty: "مساحة وتنظيم",
    status: "نشط",
  },
  {
    id: 2,
    name: "ريم عادل",
    phone: "+963 944 222 889",
    email: "reem@example.com",
    specialty: "تدقيق مخططات",
    status: "نشط",
  },
  {
    id: 3,
    name: "مازن كمال",
    phone: "+963 955 456 111",
    email: "mazen@example.com",
    specialty: "رفع مساحي",
    status: "متوقف",
  },
];